# Generated by Django 4.1.5 on 2024-03-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stuid", models.IntegerField()),
                ("studname", models.CharField(max_length=70)),
                ("studemail", models.CharField(max_length=70)),
            ],
        ),
    ]
