# Generated by Django 4.1.5 on 2024-05-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="pasword",
            new_name="password",
        ),
    ]
