# Generated by Django 4.1.5 on 2024-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="comment",
            field=models.CharField(default="Not available", max_length=40),
        ),
    ]
