# Generated by Django 4.1.5 on 2024-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="studoass",
            new_name="studpass",
        ),
        migrations.AlterField(
            model_name="student",
            name="studid",
            field=models.IntegerField(max_length=70),
        ),
    ]
